== 基础

在这个条款中指定的需要的能力作为基础选项，指定第2款规定<<_options>>和扩展第3条款规定<<_registered_extensions>>。
在这种标准下的所有gpkg_ *表和视图和所有瓦片用户数据表只有指定的列和表约束。任何用户数据表可能除了指定的列还有其他列。
所有指定的表和列的名称值将使用小写。

=== 核心

在子条款和本条款的要求中定义的强制性核心能力应当由每个*GeoPackage*和*GeoPackage SQLite的配置*来实现。

==== SQLite 容器

The SQLite software library provides a self-contained, single-file, cross-platform, serverless, transactional, open source RDBMS SQLite的软件库提供了一个自包含的，单文件，跨平台的，无服务器，事务性的，开放源码的RDBMS的容器。该geopackage规范定义了一个SQL数据库方案，此方案采用SQLite的软件库。使用SQLite作为geopackage的基础，简化了生产，分配和使用了geopackages，保证它们所包含的数据的完整性和协助。
“自包含”是指容器的软件需要来自外部库或操作系统很小的支持。 “单个文件”是指一个容器当前没有打开任何应用软件，包含由计算平台的操作系统支持的文件系统中的单个文件。 “跨平台”指的是一个容器文件可以创建和加载在一个计算平台的数据，并在另一个平台上使用和更新，即使他们使用不同的操作系统，文件系统和字节顺序（endian）的约定。 “无服务器”指的是RDBMS容器在没有任何中介服务器进程下实现，并直接由应用软件进行访问。 “交易”是指RDBMS交易保证尽管程序崩溃，操作系统崩溃，和电源故障，在容器中所有的数据改变仍是原子性，一致性，隔离和持久的（ACID）。


===== 数据

====== 文件格式

:req1_foot1: footnote:[SQLite version 4 (reference B25), which will be an alternative to version 3, not a replacement thereof, was not available when this specification was written. See Future Work clause in Annex B.]
:req1_foot2: footnote:[SQLite is in the public domain (see http://www.sqlite.org/copyright.html)]
:req2_foot1: footnote:[With SQLite versions 3.7.17 and later this value MAY be set with the "PRAGMA application_id=1196437808;" SQL statement, where 1196437808 is the 32-bit integer value of 0x47503130. With earlier versions of SQLite the application id can be set by writing the byte sequence 0x47, 0x50, 0x31, 0x30 at offset 68 in the SQLite database file (see http://www.sqlite.org/fileformat2.html#database_header for details).]

[requirement]
A GeoPackage SHALL be a http://www.sqlite.org/[SQLite] <<5>> database file using http://sqlite.org/fileformat2.html[version 3 of the SQLite file format] <<6>> <<7>>.
The first 16 bytes of a GeoPackage SHALL contain “SQLite format 3” {req1_foot1} in ASCII <<B4>>. {req1_foot2}

[requirement]
SQLite数据库头的应用ID字段应包含0x47503130（在ASCII 中的“10”），来表明是geopackage 1.0 版文件。 {req2_foot1}

GeoPackage的最大存储空间约为140TB。在实际应用中，较低存储空间可能受写入文件系统中的文件限制。许多移动设备需要外部存储卡，这些外部存储卡可以使用增加了4GB最大大小的FAT32文件系统进行格式化。

====== File Extension Name

[requirement]
geopackage应当有文件扩展名“*.gpkg”。

推荐扩展geopackages 使用文件扩展名”*.gpkx”，但这不是geopackage规范要求。

====== 文件内容

[requirement]
A GeoPackage SHALL only contain data elements, SQL constructs and GeoPackage extensions with the “gpkg” author name specified in this encoding standard.
geopackage应只包含数据元素，SQL构造和带有“.gpkg”的GeoPackage扩展。使用这种编码标准指定作者的名字。

In order to guarantee maximum interoperability between applications, GeoPackages SHALL NOT contain data elements (tables or columns), SQL constructs (data types, indexes, constraints or triggers) or extensions that are not specified in this encoding standard.
SQLite databases that use constructs from the GeoPackage specification but extend that to contain any of these elements are referred to as Extended GeoPackages throughout this specification.
为了保证应用程序之间最大的互操作性，geopackages应该不包含数据元素（表或列），SQL结构（数据类型，索引，约束或触发器）或者未使用此编码标准指定的扩展。SQLite数据库使用由geopackage规范指定但是可扩展的结构，扩展后包含任何元素被称为扩展geopackages使用整个规范。

[requirement]
The columns of tables in a GeoPackage SHALL only be declared using one of the data types specified in table <<table_column_data_types>>.
geopackage表列应仅使用在表1中指定的数据类型进行申明

[[table_column_data_types]]
.GeoPackage Data Types
[cols=",,,,,",options="header"]
|=======================================================================
|数据类型             | 大小与说明
|BOOLEAN              | A boolean value representing true or false. Stored as SQLite INTEGER with value 0 for false or 1 for true .布尔逻辑的值是true或false 
存储为SQLite的整数，值0代表false，1代表true
|TINYINT              | 8-bit signed two's complement integer. Stored as SQLite INTEGER with values in the range [-128, 127] 8位带符号二进制整形补码
存储为SQLite的整数，值的范围是[-128, 127] 
|SMALLINT             | 16-bit signed two's complement integer. Stored as SQLite INTEGER with values in the range [-32768, 32767] 16位有符号二进制补码整数 
存储为SQLite的整数，值的范围是[-32768，32767]
|MEDIUMINT            | 32-bit signed two's complement integer. Stored as SQLite INTEGER with values in the range [-2147483648, 2147483647].32位有符号二进制补码整数.存储为SQLite的整数，值的范围是[-2147483648, 2147483647] 
|INT, INTEGER         | 64-bit signed two's complement integer. Stored as SQLite INTEGER with values in the range [-9223372036854775808, 9223372036854775807].64位有符号二进制补码整数.存储为SQLite的整数，值的范围是[-9223372036854775808, 9223372036854775807] 
|FLOAT                | 32-bit IEEE floating point number. Stored as SQLite REAL limited to values that can be represented as a 4-byte IEEE floating point number.32位IEEE 浮点数.存储为SQLite的实限值可以被表示为一个4字节的IEEE浮点数
|DOUBLE, REAL         | 64-bit IEEE floating point number. Stored as SQLite REAL.64位IEEE 浮点数.存储为SQLite的实际值
|TEXT{(maxchar_count)}| Variable length string encoded in either UTF-8 or UTF-16, determined by PRAGMA encoding; see http://www.sqlite.org/pragma.html#pragma_encoding. The optional maxchar_count defines the maximum number of characters in the string. If not specified, the length is unbounded. The count is provided for informational purposes, and applications MAY choose to truncate longer strings if encountered. When present, it is best practice for applications to adhere to the character count. Stored as SQLite TEXT.由PRAGMA编码决定是使用UTF-8还是UTF-16编码长度可变的字符串;可参考http://www.sqlite.org/pragma.html#pragma_encoding  .可选参数maxchar_count定义了字符串中最大字符数目。如果未指定，则长度是无限的。计数是为了提供信息，还有当遇到问题时，在应用中可以选择截断更长的字符串。如果指定，它是坚持字数统计的最佳实际应用。存储为文本的SQLite
|BLOB{(max_size)}     | Variable length binary data. The optional max_size defines the maximum number of bytes in the blob. If not specified, the length is unbounded. The size is provided for informational purposes. When present, it is best practice for applications adhere to the maximum blob size. Stored as SQLite BLOB.长度可变的二进制数据。  可选的max_size在blob中定义了最大字节数。如果未指定，则长度是无限的。大小提供了信息参考。如果指定，它是符合最大BLOB大小的最佳实际应用。存储为SQLite的BLOB 
|<geometry_type_name> | Geometry encoded as per clause <<_geometry_encoding>>. <geometry type_name> is one of the geometry types listed in <<geometry_types>> encoded per clause 2.1.3 or a user-defined geometry type encoded per clause 3.1.2 and <<extension_geometry_encoding>>. Geometry Types XY, XYZ, XYM and XYZM geometries use the same data type. Stored as SQLite BLOB.<geometry type_name>是一种几何类型，在附录E中列出，每个句子都经过了编码。 2.1.3或3.1.2条和附录K中用户自定义的每个句子经过编码的几何数据类型。几何类型XY，XYZ，XYM和XYZM的几何要素使用的是相同数据类型。存储为BLOB的SQLite
|DATE                 | ISO-8601 date string in the form YYYY-MM-DD encoded in either UTF-8 or UTF-16. See TEXT. Stored as SQLite TEXT.以YYYY-MM-DD这种形式存在的，ISO-8601日期字符串，用UTF-8或UTF-16方式进行编码。请参见正文。 存储为文本的SQLite
|DATETIME             | ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ with T separator character and Z suffix for coordinated universal time (UTC) encoded in either UTF-8 or UTF-16. See TEXT. Stored as SQLite TEXT.以YYYY-MM-DDTHH：MM：SS.SSSZ形式存的，ISO-8601日期/时间字符串，以T分隔符和Z后缀，使用UTF-8或UTF-16编码协调世界时(UTC)。请参见正文。存储为文本的SQLite
|=======================================================================

====== File Integrity文件完整

[requirement]
The SQLite PRAGMA integrity_check SQL command SHALL return “ok” for a GeoPackage file.使用SQLite语法中的integrity_check SQL命令，将为GeoPackage返回“OK”。

[requirement]
The SQLite PRAGMA foreign_key_check SQL with no parameter value SHALL return an empty result set indicating no invalid foreign key values for a GeoPackage file.使用SQLite语法中不带参数值的foreign_key_check SQL命令，将返回一个空的结果集，表示geopackage没有无效的外键值。

===== API

[[api_sql]]
====== Structured Query Language (SQL)结构化查询语言（SQL）

:req4_foot1: footnote:[New applications should use the latest available SQLite version software <<8>>]

[requirement]
A GeoPackage SQLite Configuration SHALL provide SQL access to GeoPackage contents via http://www.sqlite.org/download.html[SQLite version 3] <<6>> software APIs.GeoPackage SQLite的配置应该提供通过SQLite3版本软件的API， 使SQL可访问GeoPackage的内容。 {req4_foot1}

====== Every GPKG SQLite Configuration Geopackage SQLite 的配置

The http://www.sqlite.org/download.html[SQLite] <<8>> library has many http://www.sqlite.org/compile.html[compile time] and http://www.sqlite.org/pragma.html[run time] options that MAY be used to configure SQLite for different uses. Certain elements of the GeoPackage specification depend on the availability of SQLite functionality at runtime. This clause specifies the set of compile- and runtime options that SHALL or SHALL NOT be used.
SQLite软件有许多编译和运行时的选项，可用于针对不同用途配置SQLite 。该GeoPackage规范的某些内容依赖于SQLite在运行时功能的可用性。这个子句指定了应该或是不应该被使用的一系列编译和运行时选项。

[requirement]
Every GeoPackage SQLite Configuration SHALL have the SQLite library compile and run time options specified in table <<every_gpkg_sqlite_config_table>>.每个geopackage SQLite配置应该有在第1.1.1.2.2Table2中指定的SQLite软件运行和编译时的选项。

[[every_gpkg_sqlite_config_table]]
.Every GeoPackage SQLite Configuration GeoPackage SQLite 配置
[cols=",,,",options="header",]
|=======================================================================
|Setting |Option |Shall / Not |Discussion
|compile |SQLITE_OMIT_* |Not |SHALL NOT include any OMIT options from http://www.sqlite.org/compile.html#omitfeatures. 不应该包括任何OMIT选项，来源于http://www.sqlite.org/compile.html#omitfeatures.
|run |PRAGMA foreign_keys |Not (OFF) |Foreign key constraints are used to maintain GeoPackage referential integrity.外键约束用来维持GeoPackage关系的完整性
|=======================================================================

[[spatial_ref_sys]]
==== Spatial Reference Systems 空间参考系统

===== 数据

[[spatial_ref_sys_data_table_definition]]
====== 表的定义

[requirement]
A GeoPackage SHALL include a `gpkg_spatial_ref_sys` table per clause 1.1.2.1.1 <<spatial_ref_sys_data_table_definition>>, Table <<gpkg_spatial_ref_sys_cols>> and Table <<gpkg_spatial_ref_sys_sql>>.geopackage规范应包括gpkg_spatial_ref_sys表的每项条款

A table named `gpkg_spatial_ref_sys` is the first component of the standard SQL schema for simple features described in clause <<sfsql_intro>> below.
The coordinate reference system definitions it contains are referenced by the GeoPackage `gpkg_contents` and `gpkg_geometry_columns` tables to relate the vector and tile data in user tables to locations on the earth.
名为gpkg_spatial_ref_sys表是标准SQL模式的第一个部分。在下面的2.1.1中描述了简单功能。坐标参考系统的定义，它包含引用的geopackage gpkg_contents和gpkg_geometry_columns表，以及与表关联的用用户表中的矢量和瓦片数据在地球上定位。

The `gpkg_spatial_ref_sys` table includes at a minimum the columns specified in SQL/MM (ISO 13249-3) <<12>> and shown in <<gpkg_spatial_ref_sys_cols>> below containing data that defines spatial reference systems.
Views of this table MAY be used to provide compatibility with the http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=53698[SQL/MM] <<12>> (see <<sqlmm_gpkg_spatial_ref_sys_sql>>) and OGC http://portal.opengeospatial.org/files/?artifact_id=25354[Simple Features SQL] <<9>><<10>><<11>> (Table 21) specifications.
该gpkg_spatial_ref_sys表至少包括在SQL / MM（ISO13249-3）规定，和在下表3中展示出的列，表3中包含定义空间参考系统的数据。 此表的视图可以用于提供与SQL /毫米的兼容性（表19）和SQL（表20）规定的OGC简单要素。

[[gpkg_spatial_ref_sys_cols]]
.Spatial Ref Sys Table Definition 空间参考系统表的定义
[cols=",,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Key
|`srs_name` |TEXT |Human readable name of this SRS 空间参考系统名字|no |
|`srs_id` |INTEGER |Unique identifier for each Spatial Reference System within a GeoPackage GeoPackage规范内每个空间参考系统唯一标识|no |PK
|`organization` |TEXT |Case-insensitive name of the defining organization e.g. EPSG or epsg 定义的组织不区分大小写，例如EPSG or epsg|no |
|`organization_coordsys_id` |INTEGER |Numeric ID of the Spatial Reference System assigned by the organization 由组织分配的空间参考系统的数字ID|no |
|`definition` |TEXT |Well-known Text <<32>> Representation of the Spatial Reference System 由文字标示的著名空间参考系统|no |
|`description` |TEXT |Human readable description of this SRS 空间参考系统描述|yes |
|=======================================================================

See <<gpkg_spatial_ref_sys_sql>>.

====== Table Data Values 表中数据值

Definition column WKT values in the gpkg_spatial_ref_sys table SHALL define the Spatial Reference Systems used by feature geometries and tile images, unless these SRS are unknown and therefore undefined as specified in <<_requirement-11>>. Values SHALL be constructed per the EBNF syntax in <<32>> clause 7. Values SHALL include optional <authority> EBNF entities. Values for SRS other than WGS-84 SHOULD include optional <to wgs84> EBNF entities. Values MAY omit optional <to wgs84> and <twin axes> EBNF entities. EBNF name and number values MAY be obtained from any specified <authority>, e.g. <<13>><<14>>. For example, see the return value in <<spatial_ref_sys_data_values_default>> Test Method step (3) used to test the definition for WGS-84 per <<_requirement-11>>:
在gpkg_spatial_ref_sys表中定义的WKT列值，将定义使用了集合要素和图片的空间参考系统。除非这些SRS是未知的，因此不需要在要求11中指定。值应该按第7条款中的EBNF语法构建。值应包括可选的<局> EBNF实体。SRS除了WGS-84外，应包括可选的< WGS84 > EBNF实体值。值可以忽略可选的< WGS84 >和< < WGS84双轴> EBNF实体。EBNF的名字和号码的值可以从任何指定的<局>获得。例如，看到A.1.1.2.1.2试验方法步骤的返回值，用于测试每个请求11 的WGS-84坐标定义。

[requirement]
The `gpkg_spatial_ref_sys` table in a GeoPackage SHALL contain a record for
organization http://www.epsg.org/Geodetic.html[EPSG] or epsg <<B3>> and `organization_coordsys_id` http://www.epsg-registry.org/report.htm?type=selection&entity=urn:ogc:def:crs:EPSG::4326&reportDetail=long&title=WGS%2084&style=urn:uuid:report-style:default-with-code&style_name=OGP%20Default%20With%20Code[4326] <<13>><<14>> for http://www.google.com/search?as_q=WGS-84[WGS-84] <<15>>, a record with an `srs_id` of -1, an organization of “NONE”, an `organization_coordsys_id` of -1, and definition “undefined” for undefined Cartesian coordinate reference systems, and a record with an `srs_id` of 0, an organization of “NONE”, an `organization_coordsys_id` of 0, and definition “undefined” for undefined geographic coordinate reference systems.在符合geopackage规范的gpkg_spatial_ref_sys表中，应当包括组织EPSG或epsg和WGS-84的organization_coordsys_id 4326记录，一个为-1的srs_id记录，一个“无”组织，一个为-1 的organization_coordsys_id组织，为未定义的笛卡尔坐标参考系定义“未定义”， 一个为0的srs_id记录，一个“无”组织，一个为0 的organization_coordsys_id组织，为未定义的地理坐标参考系统定义“未定义”。

[requirement]
The `gpkg_spatial_ref_sys` table in a GeoPackage SHALL contain records to define all spatial reference systems used by features and tiles in a GeoPackage.在符合geopackage规范的gpkg_spatial_ref_sys表中，应包含一些记录，去定义在GeoPackage中被被要素和瓦片使用的所有空间参考系统

==== 内容

===== 数据

====== 表定义

[requirement]
A GeoPackage file SHALL include a `gpkg_contents` table per table <<gpkg_contents_cols>> and <<gpkg_contents_sql>>.geopackage包括的gpkg_contents表在本章节1.1.3.1.1，表4和表21中进行了描述。

The purpose of the `gpkg_contents` table is to provide identifying and descriptive information that an application can display to a user in a menu of geospatial data that is available for access and/or update.

[[gpkg_contents_cols]]
.Contents Table or View Definition
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Type |Description |Null |Default |Key
|`table_name` |TEXT |The name of the tiles, or feature table |no | |PK
|`data_type` |TEXT |Type of data stored in the table:. “features” per clause <<features>>, “tiles” per clause <<tiles>>, or an implementer-defined value for other data tables per clause in an Extended GeoPackage. |no | |
|`identifier` |TEXT |A human-readable identifier (e.g. short name) for the table_name content |yes | |
|`description` |TEXT |A human-readable description for the table_name content |yes |“” |
|`last_change` |DATETIME |timestamp value in ISO 8601 format as defined by the strftime function '%Y-%m-%dT%H:%M:%fZ' format string applied to the current time |no |`strftime('%Y-%m-%dT%H:%M:%fZ', 'now')` |
|`min_x` |DOUBLE |Bounding box minimum easting or longitude for all content in table_name |yes | |
|`min_y` |DOUBLE |Bounding box minimum northing or latitude for all content in table_name |yes | |
|`max_x` |DOUBLE |Bounding box maximum easting or longitude for all content in table_name |yes | |
|`max_y` |DOUBLE |Bounding box maximum northing or latitude for all content in table_name |yes | |
|`srs_id` |INTEGER |Spatial Reference System ID: `gpkg_spatial_ref_sys.srs_id`; when `data_type` is features, SHALL also match `gpkg_geometry_columns.srs_id`; When data_type is tiles, SHALL also match gpkg_tile_matrix_set.srs.id |yes | |FK
|=======================================================================

The `gpkg_contents` table is intended to provide a list of all geospatial contents in a GeoPackage.
The `data_type` specifies the type of content.
The bounding box (`min_x`, `min_y`, `max_x`, `max_y`) provides an informative bounding box (not necessarily minimum bounding box) of the content.
If the `srs_id` column value references a geographic coordinate reference system (CRS), then the min/max x/y values are in decimal degrees; otherwise, the srs_id references a projected CRS and the min/max x/y values are in the units specified by that CRS.

See <<gpkg_contents_sql>>.

====== Table Data Values

[requirement]
The `table_name` column value in a `gpkg_contents` table row SHALL contain the name of a SQLite table or view.

:req13_foot1: footnote:[The following statement selects an ISO 8601timestamp value using the SQLite strftime function: SELECT (strftime('%Y-%m-%dT%H:%M:%fZ','now')).]
[requirement]
Values of the `gpkg_contents` table `last_change` column SHALL be in http://www.iso.org/iso/catalogue_detail?csnumber=40874[ISO 8601] <<29>> format containing a complete date plus UTC hours, minutes, seconds and a decimal fraction of a second, with a ‘Z’ (‘zulu’) suffix indicating UTC. {req13_foot1}

[requirement]
Values of the `gpkg_contents` table `srs_id` column SHALL reference values in the `gpkg_spatial_ref_sys` table `srs_id` column.
